Repository bonseung-dev/renewal-useNaviDate, pull requests merged in 2025-06, with the labels that each got.

#2 Feat/#1-tanstack query provider 적용
  src/app/(routes)/layout.tsx
  src/app/error.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/lib/providers/.gitignore
  src/lib/providers/tanstack-query-provider.tsx
Labels: ✨ Feature, 🌱 수진

#8 Feat/#7-google calendar api
  package.json
  pnpm-lock.yaml
  src/components/features/date-calendar/date-tab.tsx
  src/constants/.gitignore
  src/constants/holiday.constants.ts
  src/lib/services/.gitignore
  src/lib/services/holiday.services.ts
  src/types/calendar.type.ts
Labels: ✨ Feature, 📬 API, 🌱 수진

#11 Feat/#9 anniversary tab
  next.config.mjs
  src/app/(routes)/date-calendar/page.tsx
  src/app/(routes)/layout.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/features/date-calendar/anniversary/anniversary-form.tsx
  src/components/features/date-calendar/anniversary/anniversary-list.tsx
  src/components/features/date-calendar/anniversary/anniversary-tab.tsx
  src/components/features/date-calendar/calendar-tabs.tsx
  src/components/ui/number-picker.tsx
  src/constants/holiday.constants.ts
  src/lib/hooks/.gitignore
  src/lib/hooks/use-anniversaries.ts
  src/lib/utils/.gitignore
  src/lib/utils/anniversary.utils.ts
  src/types/anniversary.type.ts
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Html&css, 🌱 수진

#13 Feat/#4 share api
  db.json
  package.json
  pnpm-lock.yaml
  src/app/(routes)/couple-space/invite/[coupleId]/page.tsx
  src/app/(routes)/couple-space/page.tsx
  src/components/features/couple-space/ConnectedCoupleSpacePage.tsx
  src/components/features/couple-space/UnconnectedCouplePage.tsx
  src/lib/queries/coupleQueries.ts
  src/lib/utils/shareInviteLink.ts
  src/types/couple.type.ts
Labels: ✨ Feature, 📬 API, 👾 본승

#18 Style/#15 write date page styling
  public/emotions/emotion_angry.png
  public/emotions/emotion_excited.png
  public/emotions/emotion_happy.png
  public/emotions/emotion_sad.png
  public/emotions/emotion_usual.png
  public/search-icon.png
  public/tooltip-question-mark.png
  src/app/(routes)/write-date/page.tsx
  src/components/features/write-date/divider.tsx
  src/components/features/write-date/post-visibility-switch.tsx
  src/components/features/write-date/post-visibility-tooltip.tsx
  src/components/features/write-date/post-visibility.tsx
  src/components/features/write-date/search-address-button.tsx
  src/components/features/write-date/search-address.tsx
  src/components/features/write-date/select_emotion.tsx
  src/components/features/write-date/submit-post-button.tsx
  src/components/features/write-date/submit-post.tsx
  src/components/features/write-date/tag.tsx
  src/components/features/write-date/upload-image-carousel.tsx
  src/components/features/write-date/write-content.tsx
  src/components/ui/carousel.tsx
  src/components/ui/switch.tsx
Labels: 🎨 Html&css, ♣ 종연
