Repository bonseung-dev/renewal-useNaviDate, pull requests merged in 2025-07, with the labels that each got.

#31 Feat/#20 like bookmark 기능 구현
  .gitignore
  db.json
  pnpm-lock.yaml
  src/components/features/community/community.tsx
  src/components/features/community/post-card.tsx
  src/components/features/date-calendar/anniversary/anniversary-header.tsx
  src/components/features/date-calendar/date-tab.tsx
  src/components/features/date-calendar/date/calendar-card.tsx
  src/components/features/nav/footer.tsx
  src/components/features/nav/header.tsx
  src/components/ui/.gitignore
  src/components/ui/tooltip.tsx
  src/constants/community.constants.ts
  src/constants/emotions.constants.ts
  src/lib/hooks/community/use-community-data.ts
  src/lib/hooks/community/use-enhanced-posts.ts
  src/lib/hooks/community/use-search-query.ts
  src/lib/hooks/community/use-sorted-posts.ts
  src/lib/mutations/bookmark.mutation.ts
  src/lib/mutations/like.mutation.ts
  src/lib/queries/community.queries.ts
  src/lib/services/auth.services.ts
  src/lib/services/calendar.services.ts
  src/lib/services/community.services.ts
  src/lib/utils/cookes.utils.ts
  src/lib/utils/coomunity.utils.ts
  src/types/calendar.type.ts
  src/types/chat.typte.ts
  src/types/community.type.ts
  src/types/like-bookmark.type.ts
  src/types/notification.type.ts
  src/types/post.type.ts
  src/types/setting.type.ts
  src/types/user.type.ts
Labels: ✨ Feature, 📬 API, 🌱 수진

#30 Feat/#24 write date
  public/cancel-icon.png
  src/app/(routes)/date-detail/[dateId]/page.tsx
  src/app/(routes)/write-date/page.tsx
  src/components/features/date-detail/place-name.tsx
  src/components/features/date-detail/searched-address.tsx
  src/components/features/date-detail/uploaded-images/uploaded-image-items.tsx
  src/components/features/date-detail/uploaded-images/uploaded-images-carousel.tsx
  src/components/features/date-detail/written-content.tsx
  src/components/features/date-detail/written-tags.tsx
  src/components/features/write-date/image-items.tsx
  src/components/features/write-date/post-visibility/post-visibility-switch.tsx
  src/components/features/write-date/post-visibility/post-visibility.tsx
  src/components/features/write-date/select_emotion.tsx
  src/components/features/write-date/submit-post/submit-post-button.tsx
  src/components/features/write-date/upload-image-carousel.tsx
  src/components/features/write-date/write-content.tsx
  src/components/features/write-date/write-tag.tsx
  src/constants/path.ts
  src/constants/query-keys.constants.ts
Labels: ✨ Feature, ♣ 종연

#33 Refactor/#26 calendar refactoring
  src/app/(routes)/date-calendar/[coupleId]/page.tsx
  src/app/api/auth/delete-cookies/route.ts
  src/components/features/date-calendar/anniversary/anniversary-actions.tsx
  src/components/features/date-calendar/anniversary/anniversary-form.tsx
  src/components/features/date-calendar/anniversary/anniversary-form/anniversary-date-picker.tsx
  src/components/features/date-calendar/anniversary/anniversary-form/anniversary-editor.tsx
  src/components/features/date-calendar/anniversary/anniversary-form/anniversary-form-buttons.tsx
  src/components/features/date-calendar/anniversary/anniversary-form/anniversary-form-header.tsx
  src/components/features/date-calendar/anniversary/anniversary-form/anniversary-form.tsx
  src/components/features/date-calendar/anniversary/anniversary-form/anniversary-title-input.tsx
  src/components/features/date-calendar/anniversary/anniversary-header.tsx
  src/components/features/date-calendar/anniversary/anniversary-item.tsx
  src/components/features/date-calendar/anniversary/anniversary-list.tsx
  src/components/features/date-calendar/anniversary/anniversary-tab.tsx
  src/components/features/date-calendar/anniversary/truncated-text-with-tooltip.tsx
  src/components/features/date-calendar/calendar-tabs.tsx
  src/components/features/date-calendar/date-tab.tsx
  src/components/features/date-calendar/date/analysis-button.tsx
  src/components/features/date-calendar/date/calendar-card.tsx
  src/components/features/date-calendar/date/calendar/calendar-card.tsx
  src/components/features/date-calendar/date/calendar/calendar-day-cell.tsx
  src/components/features/date-calendar/date/calendar/calendar-header.tsx
  src/components/features/date-calendar/date/calendar/calendar-navigation.tsx
  src/components/features/date-calendar/date/calendar/calendar-weekday.tsx
  src/components/features/date-calendar/date/date-analysis.tsx
  src/components/features/date-calendar/date/frequent-places.tsx
  src/components/features/date-calendar/login-prompt.tsx
  src/components/features/nav/log-out-test.tsx
  src/components/ui/number-picker.tsx
  src/lib/hooks/date-calendar/use-anniversaries.ts
  src/lib/hooks/date-calendar/use-anniversary-actions.ts
  src/lib/hooks/date-calendar/use-anniversary-form.ts
  src/lib/hooks/date-calendar/use-partner-infor.ts
  src/lib/hooks/date-calendar/use-sorted-anniversaries.ts
  src/lib/hooks/use-anniversaries.ts
  src/lib/services/anniversary.services.ts
  src/lib/utils/anniversary.utils.ts
  src/lib/utils/calendar.utils.ts
  src/lib/utils/client-cookies.utils.ts
Labels: 🎨 Html&css, 🔨 Refactor, 🌱 수진

#37 Refactor: type 수정 #36
  src/types/anniversary.type.ts
  src/types/calendar.type.ts
  src/types/chat.typte.ts
  src/types/community.type.ts
  src/types/couple.type.ts
  src/types/image.type.ts
  src/types/like-bookmark.type.ts
  src/types/notification.type.ts
  src/types/post.type.ts
  src/types/setting.type.ts
  src/types/user.type.ts
Labels: 🔨 Refactor, 🌱 수진

#43 Refactor/#41 post detail and write post
  src/app/(routes)/date-detail/[postId]/page.tsx
  src/app/(routes)/write-date/page.tsx
  src/components/features/date-detail/buttons/bookmark-button.tsx
  src/components/features/date-detail/buttons/like-button.tsx
  src/components/features/date-detail/date-detail.tsx
  src/components/features/date-detail/uploaded-images/uploaded-image-items.tsx
  src/components/features/write-date/image-items.tsx
  src/components/features/write-date/post-visibility/post-visibility-switch.tsx
  src/components/features/write-date/post-visibility/post-visibility.tsx
  src/components/features/write-date/upload-image-carousel.tsx
  src/components/features/write-date/write-date.tsx
  src/lib/mutations/write-date.mutation.ts
  src/lib/queries/date-detail.queries.ts
  src/lib/services/date-detail.services.ts
  src/lib/services/write-date.services.ts
Labels: 🔨 Refactor, ♣ 종연
